spring.application.name=back
db.url=jdbc:postgresql://localhost:5432/blog_back_app
db.username=postgres
db.password=20Maysim_24i
db.driver=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
images.storage.path=./images
server.port=8080