spring.application.name=back
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_back_app
spring.datasource.username=postgres
spring.datasource.password=20Maysim_24i
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
images.storage.path=./images
server.port=8080